stages:
  download_example_SAR:
    cmd: python src/data/download_SAR.py --start "2020-01-13T00:00:00Z" --end "2020-01-13T23:59:59Z" --output data/SAR/OCN/
    deps:
    - src/data/download_SAR.py
    outs:
    - data/SAR/OCN
  download_SAR_GRD:
    cmd: python src/data/download_SAR.py --start "2020-01-13T00:00:00Z" --end "2020-01-13T23:59:59Z" --product GRD_HD --output data/SAR/GRD/
    deps:
    - src/data/download_SAR.py
    outs:
    - data/SAR/GRD/
  regrid_SAR:
    cmd: python src/data/regrid_SAR.py -v owiWindSpeed -i data/examples/SAR_WindSpeed_20200113.png
    deps:
    - src/data/regrid_SAR.py
    - data/SAR/
    outs:
    - data/examples/SAR_WindSpeed_20200113.png
  regrid_GOES16_ABI:
    cmd: python src/data/regrid_GOES.py -f data/GOES16/OR_ABI-L1b-RadF-M6C13_G16_s20200130940200_e20200130949519_c20200130950003.nc -c C13 -i data/examples/GOES16-ABI_BT_C13_20201130940.png
    deps:
    - src/data/regrid_GOES.py
    - data/GOES16/OR_ABI-L1b-RadF-M6C13_G16_s20200130940200_e20200130949519_c20200130950003.nc
    outs:
    - data/examples/GOES16-ABI_BT_C13_20201130940.png
