name: cpd
channels:
  - conda-forge
dependencies:
  - python
  - xarray
  - intake-xarray
  - zarr
  - dvc
  - s3fs
  - ipython
  - ca-certificates
  - certifi
  - openssl
  - dvc-s3
  - pre-commit
  - pip
  - pip:
    - asf_search
