name: cpd
channels:
  - conda-forge
dependencies:
  - python<=3.11
  - xarray
  - intake<2.0.0
  - intake-xarray
  - zarr
  - dvc
  - s3fs
  - ipython
  - ca-certificates
  - certifi
  - openssl
  - dvc-s3
  - matplotlib
  - satpy
  - ipdb
  - pre-commit
  - pyresample
  - xee
  - dvc-gdrive
  - datashader
  - cartopy
  - keras
  - dvclive
  - pip
  - pip:
    - asf_search
    - preffs @ git+https://github.com/d70-t/preffs@main
    - tensorflow[and-cuda]
