name: cpd
channels:
  - conda-forge
dependencies:
  - python<=3.11
  - xarray
  - intake<2.0.0
  - intake-xarray
  - zarr
  - dvc
  - ruamel.yaml<0.17.22  # https://sourceforge.net/p/ruamel-yaml/tickets/508/
  - s3fs
  - ipython
  - ca-certificates
  - certifi
  - openssl
  - dvc-s3
  - matplotlib
  - satpy
  - remotezip
  - ipdb
  - pre-commit
  - pyresample
  - xee
  - dvc-gdrive
  - datashader
  - cartopy
  - keras
  - dvclive
  - openexr
  - openexr-tensorflow
  - pip
  - pip:
    - asf_search
    - preffs @ git+https://github.com/d70-t/preffs@main
    - tensorflow[and-cuda]
    - tensorflow-graphics
    - tensorflow-datasets
    - tensorflow-examples @ git+https://github.com/tensorflow/examples.git@master
